### ISSUE TITLE
Custom Containers Not Working

### ISSUE THREAD

**Issue by RehanSaeed** [vuepressjs/vuepress-theme-blog#70] opened 2020-03-05 17:24 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report

Vuepress supports [custom containers](https://vuepress.vuejs.org/guide/markdown.html#custom-containers) but these don't seem to work with this theme.

![image](https://user-images.githubusercontent.com/2270364/76007370-d9192380-5f05-11ea-8288-ac2807553a8d.png)

#### Steps to reproduce

- [ ] I prepared a reproduction repo, here is the reproduction repo: 

- [x] This issue doesn't need a reproduction repro, here is the steps to reproduce

Enter the following markdown:
```
::: tip
This is a tip
:::
```

#### What is expected?

I should see the custom container.

#### What is actually happening?

I just get the text being output as is.

- `npx vuepress info`:

```
Environment Info:

  System:
    OS: Windows 10 10.0.19569
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 13.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19569.1000.0
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: ^1.3.1 => 1.3.1
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by newsbielt703** [comment] 2020-03-05 17:45
Duplicate of #20. Take a look at [vuepress-plugin-container](https://vuepress.github.io/en/plugins/container/).

**Closed by newsbielt703** 2020-03-05 17:45 UTC

**Comment by RehanSaeed** [comment] 2020-03-07 07:46
Could it not be included? Since the default theme had it, I'd expect the blog theme to be a superset of the default theme.

**Comment by newsbielt703** [comment] 2020-03-08 07:21
Expect it to be something like:
```
VuePress 
 ├── Default theme       
 ├── Blog theme        
 └── ...Other themes   

# Instead of:

VuePress 
 └── Default theme       
     ├── Blog theme        
     └── ...Other themes   
```

`Container` is not a necessary (widely used) feature for blogging. As the plugin system came out, we can leave such feature to users.
