### ISSUE TITLE
Add vuepress-plugin-container 

### ISSUE THREAD

**Issue by ChungZH** [vuepressjs/vuepress-theme-blog#76] opened 2020-03-31 05:19 UTC
## Feature request
Add vuepress-plugin-container in `theme-blog`.

#### What problem does this feature solve?

Use container in markdown files.

#### How should this be implemented in your opinion?
Add this plugin.
#### Are you willing to work on this yourself?
No.

**Comment by newsbielt703** [comment] 2020-03-31 08:42
Duplicate of #20, as it's not a widely-used feature for blogging, you can import it by yourself.

**Closed by newsbielt703** 2020-03-31 08:42 UTC
